### ISSUE TITLE
[Bug Report] Cannot find latest-linux.yml in the latest release artifacts

### ISSUE THREAD

**Issue by browser-bug** [WAClient/WALC#239]
**Describe the bug**
As described https://github.com/WAClient/WALC/discussions/238
App gets stuck in an infinite loop when starting.

```
Checking for update

DevTools listening on ws://127.0.0.1:42525/devtools/browser/700147bc-bd24-416e-8a8e-c0542bd5bbcc
Creating whatsapp client
Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/WAClient/WALC/releases/download/v0.3.2/latest-linux.yml): HttpError: 404
"method: GET url: https://github.com/WAClient/WALC/releases/download/v0.3.2/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 05 Feb 2024 14:55:31 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "DC58:21AC18:126C20FF:12B07845:65C0F6E3"
}
    at createHttpError (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at Object.newError (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
    at fetchData (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:108:50)
    at async GitHubProvider.getLatestVersion (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:115:23)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:333:24)
(node:370496) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/WAClient/WALC/releases/download/v0.3.2/latest-linux.yml): HttpError: 404
"method: GET url: https://github.com/WAClient/WALC/releases/download/v0.3.2/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 05 Feb 2024 14:55:31 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "DC58:21AC18:126C20FF:12B07845:65C0F6E3"
}
    at createHttpError (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at Object.newError (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
    at fetchData (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:108:50)
    at async GitHubProvider.getLatestVersion (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:115:23)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_walcLnxUE6/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:333:24)
(Use `walc --trace-warnings ...` to show where the warning was created)
(node:370496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(walc:370496): LIBDBUSMENU-GLIB-WARNING **: 15:55:37.412: About to Show called on an item wihtout submenus.  We're ignoring it.

(walc:370496): LIBDBUSMENU-GLIB-WARNING **: 15:55:37.416: About to Show called on an item wihtout submenus.  We're ignoring it.

(walc:370496): LIBDBUSMENU-GLIB-WARNING **: 15:55:37.422: About to Show called on an item wihtout submenus.  We're ignoring it.

(walc:370496): LIBDBUSMENU-GLIB-WARNING **: 15:56:09.145: About to Show called on an item wihtout submenus.  We're ignoring it.

(walc:370496): LIBDBUSMENU-GLIB-WARNING **: 15:56:09.146: About to Show called on an item wihtout submenus.  We're ignoring it.
```

Seems like the code is looking for an URL that does not exist:
´´´
"method: GET url: [https://github.com/WAClient/WALC/releases/download/v0.3.2/latest-linux.yml\n\nPlease](https://github.com/WAClient/WALC/releases/download/v0.3.2/latest-linux.yml%5Cn%5CnPlease) double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
´´´

**WALC Installation Type:** AppImage / Snap
AppImage, v0.3.2

**To Reproduce**
Just open the app.

**Did you try closing and then opening it back?:** Yes

**Screenshots**
https://github.com/WAClient/WALC/assets/44030022/1ff1c2a7-91a4-4e59-84de-6bb5df691799

**System Information (please complete the following information):**
OS: Arch Linux x86_64
Kernel: 6.7.2-arch1-1
DE: Plasma 5.27.10

**Comment by wokawoka** [comment]
I'm experiencing the same issue

**Comment by pmsobrado** [comment]
> I'm experiencing the same issue

I guess we all are, or at least the ones who still uses WALC xD

**Comment by pmsobrado** [comment]
I was just answering you, I don't think your message is unnecessary :)

**Comment by daffamumtaz2361** [comment]
Sorry for the long response. I have released a new update that should fix this issue

Please let me know here if the issue persists

**Comment by wokawoka** [comment]
I am using the new version and all I can get is a black screen on the app. The notification is correctly showing the unread message count, though.
Thank you

**Comment by pmsobrado** [comment]
Checked, works OK! Thanks!

**Comment by pmsobrado** [comment]
@Zzombiee2361 BTW, is there an "app" settings? I think I recall I could select some WALC options...

**Comment by daffamumtaz2361** [comment]
@pmsobrado there should be a dashboard button on the right side of your profile. Or you could press `alt` to show the menu bar, then you can open the dashboard from there

**Comment by pmsobrado** [comment]
@Zzombiee2361 thanks, I tred the alt button before but it didn't work and I thought maybe something was wrong, it is working now, thanks!

**Comment by browser-bug** [comment]
> Sorry for the long response. I have released a new update that should fix this issue
> 
> Please let me know here if the issue persists

I still get the same behavior. I'm using the AppImage directly downloaded from the v0.3.3 release.

**Comment by daffamumtaz2361** [comment]
@pmsobrado please do tell me, is the WALC dashboard icon not showing up to you?

**Comment by pmsobrado** [comment]
@Zzombiee2361 I don't see any button:

![imagen](https://github.com/WAClient/WALC/assets/17699739/f6687fcc-091b-4143-b5f4-ef9517c59de2)

But I can access the menu pressing Alt.
